# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ml.proto\x12\x04mlpb\"\'\n\x11TranscribeRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"@\n\x14TranscriptionSegment\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\"T\n\x12TranscribeResponse\x12\x10\n\x08language\x18\x01 \x01(\t\x12,\n\x08segments\x18\x02 \x03(\x0b\x32\x1a.mlpb.TranscriptionSegment\"R\n\x0e\x45motionRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12,\n\x08segments\x18\x02 \x03(\x0b\x32\x1a.mlpb.TranscriptionSegment\"^\n\rEmotionResult\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0f\n\x07\x65motion\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"8\n\x0f\x45motionResponse\x12%\n\x08segments\x18\x01 \x03(\x0b\x32\x13.mlpb.EmotionResult2Y\n\x14TranscriptionService\x12\x41\n\nTranscribe\x12\x17.mlpb.TranscribeRequest\x1a\x18.mlpb.TranscribeResponse\"\x00\x32S\n\x0e\x45motionService\x12\x41\n\x10\x43lassifyEmotions\x12\x14.mlpb.EmotionRequest\x1a\x15.mlpb.EmotionResponse\"\x00\x42\x42Z@github.com/yuchia329/video_semantic_search/backend/internal/mlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/yuchia329/video_semantic_search/backend/internal/mlpb'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=18
  _globals['_TRANSCRIBEREQUEST']._serialized_end=57
  _globals['_TRANSCRIPTIONSEGMENT']._serialized_start=59
  _globals['_TRANSCRIPTIONSEGMENT']._serialized_end=123
  _globals['_TRANSCRIBERESPONSE']._serialized_start=125
  _globals['_TRANSCRIBERESPONSE']._serialized_end=209
  _globals['_EMOTIONREQUEST']._serialized_start=211
  _globals['_EMOTIONREQUEST']._serialized_end=293
  _globals['_EMOTIONRESULT']._serialized_start=295
  _globals['_EMOTIONRESULT']._serialized_end=389
  _globals['_EMOTIONRESPONSE']._serialized_start=391
  _globals['_EMOTIONRESPONSE']._serialized_end=447
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=449
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=538
  _globals['_EMOTIONSERVICE']._serialized_start=540
  _globals['_EMOTIONSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
