# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/mlpb.TranscriptionService/Transcribe',
                request_serializer=ml__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=ml__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=ml__pb2.TranscribeRequest.FromString,
                    response_serializer=ml__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlpb.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlpb.TranscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlpb.TranscriptionService/Transcribe',
            ml__pb2.TranscribeRequest.SerializeToString,
            ml__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EmotionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyEmotions = channel.unary_unary(
                '/mlpb.EmotionService/ClassifyEmotions',
                request_serializer=ml__pb2.EmotionRequest.SerializeToString,
                response_deserializer=ml__pb2.EmotionResponse.FromString,
                _registered_method=True)


class EmotionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyEmotions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyEmotions': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyEmotions,
                    request_deserializer=ml__pb2.EmotionRequest.FromString,
                    response_serializer=ml__pb2.EmotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlpb.EmotionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mlpb.EmotionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmotionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyEmotions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mlpb.EmotionService/ClassifyEmotions',
            ml__pb2.EmotionRequest.SerializeToString,
            ml__pb2.EmotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
