// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatResponse struct {
	Answer     string          `json:"answer"`
	Thinking   *string         `json:"thinking,omitempty"`
	References []*SearchResult `json:"references"`
}

type FinalizeVideoInput struct {
	VideoID string `json:"videoId"`
}

type Mutation struct {
}

type Query struct {
}

type SearchResult struct {
	VideoID    string  `json:"videoId"`
	VideoTitle string  `json:"videoTitle"`
	VideoS3Key string  `json:"videoS3Key"`
	Timestamp  float64 `json:"timestamp"`
	Text       *string `json:"text,omitempty"`
	Type       string  `json:"type"`
}

type UploadResponse struct {
	UploadURL string `json:"uploadUrl"`
	VideoID   string `json:"videoId"`
	S3Key     string `json:"s3Key"`
}

type UploadVideoInput struct {
	Title       string `json:"title"`
	Filename    string `json:"filename"`
	ContentType string `json:"contentType"`
}

type Video struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Status    string  `json:"status"`
	Summary   *string `json:"summary,omitempty"`
	S3Key     string  `json:"s3Key"`
	CreatedAt string  `json:"createdAt"`
}

type YouTubeInput struct {
	URL string `json:"url"`
}
