// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChatMessage struct {
	ID        string `json:"id"`
	SessionID string `json:"sessionId"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type ChatSession struct {
	ID        string `json:"id"`
	VideoID   string `json:"videoId"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Video struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Status    string  `json:"status"`
	Summary   *string `json:"summary,omitempty"`
	Analysis  *string `json:"analysis,omitempty"`
	CreatedAt string  `json:"createdAt"`
}
