package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	"github.com/yuchia329/video_semantic_search/backend/graph/model"
	"github.com/yuchia329/video_semantic_search/backend/internal/worker"
)

// ─── Mutations ────────────────────────────────────────────────────────────────

// UploadVideo registers a new video in the DB and enqueues it for processing.
func (r *mutationResolver) UploadVideo(ctx context.Context, title string, s3Key string) (*model.Video, error) {
	var id int
	err := r.DB.Pool.QueryRow(ctx,
		`INSERT INTO videos (title, s3_key, status) VALUES ($1, $2, 'queued') RETURNING id`,
		title, s3Key,
	).Scan(&id)
	if err != nil {
		return nil, fmt.Errorf("insert video: %w", err)
	}

	// Publish Kafka event so the worker processor picks it up.
	type processEvent struct {
		VideoID string `json:"video_id"`
		S3Key   string `json:"s3_key"`
	}
	if r.Producer != nil {
		if err := r.Producer.ProduceEvent(ctx, strconv.Itoa(id), processEvent{
			VideoID: strconv.Itoa(id),
			S3Key:   s3Key,
		}); err != nil {
			return nil, fmt.Errorf("enqueue video: %w", err)
		}
	}

	return r.queryVideo(ctx, strconv.Itoa(id))
}

// DeleteVideo removes a video and its cascading chat data.
func (r *mutationResolver) DeleteVideo(ctx context.Context, id string) (bool, error) {
	tag, err := r.DB.Pool.Exec(ctx, `DELETE FROM videos WHERE id=$1`, id)
	if err != nil {
		return false, fmt.Errorf("delete video: %w", err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreateChatSession opens a new conversation session for a video.
func (r *mutationResolver) CreateChatSession(ctx context.Context, videoID string) (*model.ChatSession, error) {
	var id int
	var createdAt string
	err := r.DB.Pool.QueryRow(ctx,
		`INSERT INTO chat_sessions (video_id) VALUES ($1) RETURNING id, created_at::text`,
		videoID,
	).Scan(&id, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("create chat session: %w", err)
	}
	return &model.ChatSession{
		ID:        strconv.Itoa(id),
		VideoID:   videoID,
		CreatedAt: createdAt,
	}, nil
}

// SendMessage routes a user message through the VLM and persists both turns.
func (r *mutationResolver) SendMessage(ctx context.Context, sessionID string, message string) (*model.ChatMessage, error) {
	// 1. Look up the video_id for this session.
	var videoID int
	err := r.DB.Pool.QueryRow(ctx,
		`SELECT video_id FROM chat_sessions WHERE id=$1`, sessionID,
	).Scan(&videoID)
	if err != nil {
		return nil, fmt.Errorf("session not found: %w", err)
	}

	// 2. Fetch the stored video analysis (the VLM's initial deep-dive).
	var analysis string
	_ = r.DB.Pool.QueryRow(ctx,
		`SELECT COALESCE(analysis, '') FROM videos WHERE id=$1`, videoID,
	).Scan(&analysis)

	if analysis == "" {
		return nil, fmt.Errorf("video analysis not ready yet — please wait for processing to complete")
	}

	// 3. Load prior chat history for this session (ordered by creation time).
	rows, err := r.DB.Pool.Query(ctx,
		`SELECT role, content FROM chat_messages WHERE session_id=$1 ORDER BY id ASC`,
		sessionID,
	)
	if err != nil {
		return nil, fmt.Errorf("load history: %w", err)
	}
	var history []worker.ChatTurn
	for rows.Next() {
		var turn worker.ChatTurn
		rows.Scan(&turn.Role, &turn.Content)
		history = append(history, turn)
	}
	rows.Close()

	// 4. Persist the user message.
	_, err = r.DB.Pool.Exec(ctx,
		`INSERT INTO chat_messages (session_id, role, content) VALUES ($1, 'user', $2)`,
		sessionID, message,
	)
	if err != nil {
		return nil, fmt.Errorf("save user message: %w", err)
	}

	// 5. Call the VLM.
	reply, err := worker.ChatWithVideo(analysis, history, message)
	if err != nil {
		return nil, fmt.Errorf("VLM call failed: %w", err)
	}

	// 6. Persist the assistant reply and return it.
	var msgID int
	var createdAt string
	err = r.DB.Pool.QueryRow(ctx,
		`INSERT INTO chat_messages (session_id, role, content) VALUES ($1, 'assistant', $2) RETURNING id, created_at::text`,
		sessionID, reply,
	).Scan(&msgID, &createdAt)
	if err != nil {
		return nil, fmt.Errorf("save assistant message: %w", err)
	}

	return &model.ChatMessage{
		ID:        strconv.Itoa(msgID),
		SessionID: sessionID,
		Role:      "assistant",
		Content:   reply,
		CreatedAt: createdAt,
	}, nil
}

// ─── Queries ─────────────────────────────────────────────────────────────────

// Videos returns all videos, newest first.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	rows, err := r.DB.Pool.Query(ctx,
		`SELECT id, title, status, COALESCE(summary,''), COALESCE(analysis,''), created_at::text
		 FROM videos ORDER BY id DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var videos []*model.Video
	for rows.Next() {
		v := &model.Video{}
		var id int
		rows.Scan(&id, &v.Title, &v.Status, &v.Summary, &v.Analysis, &v.CreatedAt)
		v.ID = strconv.Itoa(id)
		videos = append(videos, v)
	}
	return videos, nil
}

// Video returns a single video by ID.
func (r *queryResolver) Video(ctx context.Context, id string) (*model.Video, error) {
	return r.queryVideo(ctx, id)
}

// ChatHistory returns all messages for a session in order.
func (r *queryResolver) ChatHistory(ctx context.Context, sessionID string) ([]*model.ChatMessage, error) {
	rows, err := r.DB.Pool.Query(ctx,
		`SELECT id, session_id, role, content, created_at::text
		 FROM chat_messages WHERE session_id=$1 ORDER BY id ASC`,
		sessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var msgs []*model.ChatMessage
	for rows.Next() {
		m := &model.ChatMessage{}
		var id, sid int
		rows.Scan(&id, &sid, &m.Role, &m.Content, &m.CreatedAt)
		m.ID = strconv.Itoa(id)
		m.SessionID = strconv.Itoa(sid)
		msgs = append(msgs, m)
	}
	return msgs, nil
}

// ─── Resolver registration ───────────────────────────────────────────────────

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// ─── Shared helpers ──────────────────────────────────────────────────────────

func (r *Resolver) queryVideo(ctx context.Context, id string) (*model.Video, error) {
	v := &model.Video{}
	var vid int
	err := r.DB.Pool.QueryRow(ctx,
		`SELECT id, title, status, COALESCE(summary,''), COALESCE(analysis,''), created_at::text
		 FROM videos WHERE id=$1`, id,
	).Scan(&vid, &v.Title, &v.Status, &v.Summary, &v.Analysis, &v.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("video not found: %w", err)
	}
	v.ID = strconv.Itoa(vid)
	return v, nil
}
