package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
	"github.com/yuchia329/video_semantic_search/backend/graph/model"
	"github.com/yuchia329/video_semantic_search/backend/internal/worker"
)

// RequestVideoUpload is the resolver for the requestVideoUpload field.
func (r *mutationResolver) RequestVideoUpload(ctx context.Context, input model.UploadVideoInput) (*model.UploadResponse, error) {
	// 0. Check limit
	var count int
	r.DB.Pool.QueryRow(ctx, "SELECT count(*) FROM videos").Scan(&count)
	if count >= 2 {
		return nil, fmt.Errorf("upload limit reached: maximum 2 videos allowed")
	}

	// 1. Insert into DB to get ID
	var id string
	err := r.DB.Pool.QueryRow(ctx, "INSERT INTO videos (title, s3_key, status) VALUES ($1, $2, 'uploading') RETURNING id::text", input.Title, "pending").Scan(&id)
	if err != nil {
		return nil, fmt.Errorf("failed to create video record: %w", err)
	}

	// 2. Generate S3 key
	s3Key := fmt.Sprintf("raw/%s_%s", id, input.Filename)

	// Update the s3_key in DB
	_, err = r.DB.Pool.Exec(ctx, "UPDATE videos SET s3_key = $1 WHERE id = $2", s3Key, id)
	if err != nil {
		return nil, fmt.Errorf("failed to update s3 key: %w", err)
	}

	// 3. Generate presigned URL
	url, err := r.S3Client.GeneratePresignedUploadURL(ctx, s3Key, 15*time.Minute)
	if err != nil {
		return nil, err
	}

	return &model.UploadResponse{
		UploadURL: url,
		VideoID:   id,
		S3Key:     s3Key,
	}, nil
}

// FinalizeVideoUpload is the resolver for the finalizeVideoUpload field.
func (r *mutationResolver) FinalizeVideoUpload(ctx context.Context, input model.FinalizeVideoInput) (*model.Video, error) {
	var v model.Video
	var summary *string
	var createdAt time.Time
	err := r.DB.Pool.QueryRow(ctx, "UPDATE videos SET status = 'processing' WHERE id = $1 RETURNING id::text, title, s3_key, status, summary, created_at", input.VideoID).
		Scan(&v.ID, &v.Title, &v.S3Key, &v.Status, &summary, &createdAt)
	if err != nil {
		return nil, err
	}
	v.CreatedAt = createdAt.Format(time.RFC3339)
	if summary != nil {
		v.Summary = summary
	}

	// Produce to Kafka
	event := worker.ProcessVideoEvent{
		VideoID: v.ID,
		S3Key:   v.S3Key,
	}
	r.Producer.ProduceEvent(ctx, v.ID, event)

	return &v, nil
}

// ProcessYouTubeVideo is the resolver for the processYouTubeVideo field.
func (r *mutationResolver) ProcessYouTubeVideo(ctx context.Context, input model.YouTubeInput) (*model.Video, error) {
	// 0. Check limit
	var count int
	r.DB.Pool.QueryRow(ctx, "SELECT count(*) FROM videos").Scan(&count)
	if count >= 2 {
		return nil, fmt.Errorf("upload limit reached: maximum 2 videos allowed")
	}

	var id string
	err := r.DB.Pool.QueryRow(ctx, "INSERT INTO videos (title, s3_key, status) VALUES ('YouTube Video', $1, 'processing') RETURNING id::text", input.URL).Scan(&id)
	if err != nil {
		return nil, err
	}

	// Produce to Kafka, worker will know it's youtube if it starts with http
	event := worker.ProcessVideoEvent{
		VideoID: id,
		S3Key:   input.URL,
	}
	r.Producer.ProduceEvent(ctx, id, event)

	var v model.Video
	v.ID = id
	v.Title = "YouTube Video"
	v.S3Key = input.URL
	v.Status = "processing"
	v.CreatedAt = time.Now().Format(time.RFC3339)

	return &v, nil
}

// DeleteVideo is the resolver for the deleteVideo field.
func (r *mutationResolver) DeleteVideo(ctx context.Context, videoID string) (bool, error) {
	// 1. Get S3 key
	var s3Key string
	err := r.DB.Pool.QueryRow(ctx, "SELECT s3_key FROM videos WHERE id = $1", videoID).Scan(&s3Key)
	if err != nil {
		return false, fmt.Errorf("video not found: %w", err)
	}

	// 2. Delete from S3 (if not youtube link)
	if s3Key != "" && s3Key[:4] != "http" {
		_ = r.S3Client.DeleteFile(ctx, s3Key)
	}

	// 3. Delete from DB
	_, _ = r.DB.Pool.Exec(ctx, "DELETE FROM visual_chunks WHERE video_id = $1", videoID)
	_, _ = r.DB.Pool.Exec(ctx, "DELETE FROM transcript_chunks WHERE video_id = $1", videoID)
	_, err = r.DB.Pool.Exec(ctx, "DELETE FROM videos WHERE id = $1", videoID)
	if err != nil {
		return false, fmt.Errorf("failed to delete video record: %w", err)
	}

	return true, nil
}

// GetVideoSummary is the resolver for the getVideoSummary field.
func (r *queryResolver) GetVideoSummary(ctx context.Context, videoID string) (*model.Video, error) {
	var v model.Video
	var summary *string
	var createdAt time.Time
	err := r.DB.Pool.QueryRow(ctx, "SELECT id::text, title, s3_key, status, summary, created_at FROM videos WHERE id = $1", videoID).
		Scan(&v.ID, &v.Title, &v.S3Key, &v.Status, &summary, &createdAt)
	if err != nil {
		return nil, err
	}
	v.CreatedAt = createdAt.Format(time.RFC3339)
	if summary != nil {
		v.Summary = summary
	}
	return &v, nil
}

// SemanticSearch is the resolver for the semanticSearch field.
func (r *queryResolver) SemanticSearch(ctx context.Context, videoID *string, query string, limit *int32) ([]*model.SearchResult, error) {
	limitVal := 5
	if limit != nil {
		limitVal = int(*limit)
	}

	// Get Text Embedding (BGE-m3) — used for both transcript and visual chunk search
	textEmbedding, err := getEmbedding("http://localhost:8901/embed", query)
	if err != nil {
		return nil, fmt.Errorf("failed to get text embedding: %w", err)
	}

	if textEmbedding == nil {
		return nil, nil
	}

	embVec := pgvector.NewVector(textEmbedding)

	// Give each modality its own allocation to ensure both are represented
	perSourceLimit := limitVal
	if perSourceLimit < 3 {
		perSourceLimit = 3
	}

	var audioResults []*model.SearchResult
	var visualResults []*model.SearchResult

	// Query Transcript Chunks
	{
		q := `
			SELECT v.id::text, v.title, v.s3_key, t.start_time, t.text 
			FROM transcript_chunks t 
			JOIN videos v ON t.video_id = v.id 
		`
		args := []interface{}{embVec, perSourceLimit}
		if videoID != nil {
			q += ` WHERE v.id = $3 `
			args = append(args, *videoID)
		}
		q += ` ORDER BY t.embedding <-> $1 LIMIT $2`

		rows, err := r.DB.Pool.Query(ctx, q, args...)
		if err != nil {
			log.Printf("Transcript query error: %v", err)
		} else {
			defer rows.Close()
			for rows.Next() {
				var res model.SearchResult
				var ts float64
				var txt string
				if err := rows.Scan(&res.VideoID, &res.VideoTitle, &res.VideoS3Key, &ts, &txt); err == nil {
					res.Timestamp = ts
					res.Text = &txt
					res.Type = "audio"
					audioResults = append(audioResults, &res)
				}
			}
		}
	}

	// Query Visual Chunks (same BGE-m3 embedding space — captions are text-embedded)
	{
		q := `
			SELECT v.id::text, v.title, v.s3_key, vc.timestamp, vc.text 
			FROM visual_chunks vc 
			JOIN videos v ON vc.video_id = v.id 
		`
		args := []interface{}{embVec, perSourceLimit}
		if videoID != nil {
			q += ` WHERE v.id = $3 `
			args = append(args, *videoID)
		}
		q += ` ORDER BY vc.embedding <-> $1 LIMIT $2`

		rows, err := r.DB.Pool.Query(ctx, q, args...)
		if err != nil {
			log.Printf("Visual query error: %v", err)
		} else {
			defer rows.Close()
			for rows.Next() {
				var res model.SearchResult
				var ts float64
				var txt *string
				if err := rows.Scan(&res.VideoID, &res.VideoTitle, &res.VideoS3Key, &ts, &txt); err == nil {
					res.Timestamp = ts
					res.Text = txt
					res.Type = "visual"
					visualResults = append(visualResults, &res)
				}
			}
		}
	}

	// Interleave results: ensure both modalities are represented
	var results []*model.SearchResult
	results = append(results, audioResults...)
	results = append(results, visualResults...)

	log.Printf("SemanticSearch: %d audio + %d visual = %d total results (limit %d)", len(audioResults), len(visualResults), len(results), limitVal)

	return results, nil
}

// ChatWithVideo is the resolver for the chatWithVideo field.
func (r *queryResolver) ChatWithVideo(ctx context.Context, videoID string, message string, history []string) (*model.ChatResponse, error) {
	limit := int32(5)
	results, err := r.SemanticSearch(ctx, &videoID, message, &limit)
	if err != nil {
		return nil, fmt.Errorf("search failed: %w", err)
	}

	contextText := ""
	for _, res := range results {
		ts := fmt.Sprintf("[%d:%02d]", int(res.Timestamp)/60, int(res.Timestamp)%60)
		if res.Text != nil && *res.Text != "" {
			contextText += fmt.Sprintf("%s (%s) %s\n", ts, res.Type, *res.Text)
		} else if res.Type == "visual" {
			contextText += fmt.Sprintf("%s (visual match) [A video frame at this timestamp matched the query visually]\n", ts)
		}
	}

	messages := []map[string]string{
		{"role": "system", "content": "You are a helpful AI assistant. Answer the user's question about the video based ONLY on the provided context snippets. Context includes audio transcript excerpts and visual frame matches. Visual matches mean a video frame at that timestamp is relevant to the query, even if no text description is available. Be conversational. Context:\n" + contextText},
	}
	for i := 0; i < len(history)-1; i += 2 {
		if i+1 < len(history) {
			messages = append(messages, map[string]string{"role": "user", "content": history[i]})
			messages = append(messages, map[string]string{"role": "assistant", "content": history[i+1]})
		}
	}
	messages = append(messages, map[string]string{"role": "user", "content": message})

	reqBody, _ := json.Marshal(map[string]interface{}{
		"model":      "Qwen/Qwen3.5-35B-A3B-GPTQ-Int4",
		"messages":   messages,
		"max_tokens": 1024,
	})

	resp, err := http.Post("http://localhost:8900/v1/chat/completions", "application/json", bytes.NewBuffer(reqBody))
	if err != nil {
		return nil, fmt.Errorf("llm request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read llm response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("LLM service returned error (status %d). Check if the vLLM server and SSH tunnel on port 8900 are running", resp.StatusCode)
	}

	var llmRes struct {
		Choices []struct {
			Message struct {
				Content   *string `json:"content"`
				Reasoning *string `json:"reasoning"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.Unmarshal(respBody, &llmRes); err != nil {
		log.Printf("Failed to decode LLM response: %v, body: %s", err, string(respBody))
		return nil, fmt.Errorf("failed to decode LLM response: %w", err)
	}

	if len(llmRes.Choices) == 0 {
		log.Printf("LLM returned 0 choices. Body: %s", string(respBody))
		return nil, fmt.Errorf("LLM returned no answer. Raw response: %s", string(respBody))
	}

	// Answer comes ONLY from content; thinking comes ONLY from reasoning
	answer := ""
	if llmRes.Choices[0].Message.Content != nil {
		answer = *llmRes.Choices[0].Message.Content
	}

	var thinking *string
	if llmRes.Choices[0].Message.Reasoning != nil && *llmRes.Choices[0].Message.Reasoning != "" {
		thinking = llmRes.Choices[0].Message.Reasoning
	}

	// If model exhausted tokens on thinking and produced no answer, retry with thinking disabled
	if answer == "" {
		log.Println("LLM content was empty (tokens exhausted on thinking). Retrying without thinking.")
		retryBody, _ := json.Marshal(map[string]interface{}{
			"model":      "Qwen/Qwen3.5-35B-A3B-GPTQ-Int4",
			"messages":   messages,
			"max_tokens": 1024,
			"chat_template_kwargs": map[string]interface{}{
				"enable_thinking": false,
			},
		})
		retryResp, err := http.Post("http://localhost:8900/v1/chat/completions", "application/json", bytes.NewBuffer(retryBody))
		if err != nil {
			return nil, fmt.Errorf("llm retry failed: %w", err)
		}
		defer retryResp.Body.Close()
		retryRespBody, _ := io.ReadAll(retryResp.Body)
		if retryResp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("LLM retry returned error (status %d)", retryResp.StatusCode)
		}
		var retryRes struct {
			Choices []struct {
				Message struct {
					Content *string `json:"content"`
				} `json:"message"`
			} `json:"choices"`
		}
		if err := json.Unmarshal(retryRespBody, &retryRes); err != nil {
			return nil, fmt.Errorf("failed to decode LLM retry response: %w", err)
		}
		if len(retryRes.Choices) > 0 && retryRes.Choices[0].Message.Content != nil {
			answer = *retryRes.Choices[0].Message.Content
		}
		if answer == "" {
			return nil, fmt.Errorf("LLM returned no answer even after retry")
		}
	}

	return &model.ChatResponse{
		Answer:     answer,
		Thinking:   thinking,
		References: results,
	}, nil
}

// GetAllVideos is the resolver for the getAllVideos field.
func (r *queryResolver) GetAllVideos(ctx context.Context) ([]*model.Video, error) {
	rows, err := r.DB.Pool.Query(ctx, "SELECT id::text, title, s3_key, status, summary, created_at FROM videos ORDER BY created_at DESC")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var videos []*model.Video
	for rows.Next() {
		var v model.Video
		var summary *string
		var createdAt time.Time
		if err := rows.Scan(&v.ID, &v.Title, &v.S3Key, &v.Status, &summary, &createdAt); err != nil {
			continue
		}
		v.CreatedAt = createdAt.Format(time.RFC3339)
		if summary != nil {
			v.Summary = summary
		}
		videos = append(videos, &v)
	}
	return videos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
