package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"

	"github.com/yuchia329/video_semantic_search/backend/graph/model"
	"github.com/yuchia329/video_semantic_search/backend/internal/worker"
)

// UploadVideo registers a new video in the DB and enqueues it for processing.
func (r *mutationResolver) UploadVideo(ctx context.Context, title string, s3Key string) (*model.Video, error) {
	userID := userIDFromCtx(ctx)

	// Enforce per-user limit of 3 non-demo videos.
	var count int
	if err := r.DB.Pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM videos WHERE user_id=$1 AND is_demo=FALSE`, userID,
	).Scan(&count); err == nil && count >= 3 {
		return nil, fmt.Errorf("upload limit reached: delete a video before uploading a new one")
	}

	var id int
	if err := r.DB.Pool.QueryRow(ctx,
		`INSERT INTO videos (title, s3_key, status, user_id) VALUES ($1, $2, 'queued', $3) RETURNING id`,
		title, s3Key, userID,
	).Scan(&id); err != nil {
		return nil, fmt.Errorf("insert video: %w", err)
	}

	return dbQueryVideo(ctx, r.DB, strconv.Itoa(id))
}

// DeleteVideo removes a video and its cascading chat data (ownership enforced).
func (r *mutationResolver) DeleteVideo(ctx context.Context, id string) (bool, error) {
	userID := userIDFromCtx(ctx)
	tag, err := r.DB.Pool.Exec(ctx,
		`DELETE FROM videos WHERE id=$1 AND user_id=$2 AND is_demo=FALSE`,
		id, userID,
	)
	if err != nil {
		return false, fmt.Errorf("delete video: %w", err)
	}
	return tag.RowsAffected() > 0, nil
}

// CreateChatSession opens a new conversation session for a video.
func (r *mutationResolver) CreateChatSession(ctx context.Context, videoID string) (*model.ChatSession, error) {
	var id int
	var createdAt string
	if err := r.DB.Pool.QueryRow(ctx,
		`INSERT INTO chat_sessions (video_id) VALUES ($1) RETURNING id, created_at::text`,
		videoID,
	).Scan(&id, &createdAt); err != nil {
		return nil, fmt.Errorf("create chat session: %w", err)
	}
	return &model.ChatSession{
		ID:        strconv.Itoa(id),
		VideoID:   videoID,
		CreatedAt: createdAt,
	}, nil
}

// SendMessage routes a user message through the VLM and persists both turns.
func (r *mutationResolver) SendMessage(ctx context.Context, sessionID string, message string) (*model.ChatMessage, error) {
	var videoID int
	if err := r.DB.Pool.QueryRow(ctx,
		`SELECT video_id FROM chat_sessions WHERE id=$1`, sessionID,
	).Scan(&videoID); err != nil {
		return nil, fmt.Errorf("session not found: %w", err)
	}

	var analysis string
	_ = r.DB.Pool.QueryRow(ctx,
		`SELECT COALESCE(analysis, '') FROM videos WHERE id=$1`, videoID,
	).Scan(&analysis)

	if analysis == "" {
		return nil, fmt.Errorf("video analysis not ready yet — please wait for processing to complete")
	}

	rows, err := r.DB.Pool.Query(ctx,
		`SELECT role, content FROM chat_messages WHERE session_id=$1 ORDER BY id ASC`,
		sessionID,
	)
	if err != nil {
		return nil, fmt.Errorf("load history: %w", err)
	}
	var history []worker.ChatTurn
	for rows.Next() {
		var turn worker.ChatTurn
		rows.Scan(&turn.Role, &turn.Content)
		history = append(history, turn)
	}
	rows.Close()

	if _, err := r.DB.Pool.Exec(ctx,
		`INSERT INTO chat_messages (session_id, role, content) VALUES ($1, 'user', $2)`,
		sessionID, message,
	); err != nil {
		return nil, fmt.Errorf("save user message: %w", err)
	}

	reply, err := worker.ChatWithVideo(ctx, r.WorkerConfig, analysis, history, message)
	if err != nil {
		return nil, fmt.Errorf("VLM call failed: %w", err)
	}

	var msgID int
	var createdAt string
	if err := r.DB.Pool.QueryRow(ctx,
		`INSERT INTO chat_messages (session_id, role, content) VALUES ($1, 'assistant', $2) RETURNING id, created_at::text`,
		sessionID, reply,
	).Scan(&msgID, &createdAt); err != nil {
		return nil, fmt.Errorf("save assistant message: %w", err)
	}

	return &model.ChatMessage{
		ID:        strconv.Itoa(msgID),
		SessionID: sessionID,
		Role:      "assistant",
		Content:   reply,
		CreatedAt: createdAt,
	}, nil
}

// Videos returns demo videos + the calling user's own videos, newest first.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	userID := userIDFromCtx(ctx)
	rows, err := r.DB.Pool.Query(ctx,
		`SELECT id, title, status,
		        COALESCE(summary,''),
		        COALESCE(analysis,''),
		        COALESCE(user_id,'anonymous'),
		        is_demo,
		        created_at::text
		 FROM videos
		 WHERE is_demo=TRUE OR user_id=$1
		 ORDER BY is_demo DESC, id DESC`,
		userID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var videos []*model.Video
	for rows.Next() {
		v := &model.Video{}
		var id int
		if err := rows.Scan(&id, &v.Title, &v.Status, &v.Summary, &v.Analysis, &v.UserID, &v.IsDemo, &v.CreatedAt); err != nil {
			continue
		}
		v.ID = strconv.Itoa(id)
		videos = append(videos, v)
	}
	return videos, nil
}

// Video returns a single video by ID.
func (r *queryResolver) Video(ctx context.Context, id string) (*model.Video, error) {
	return dbQueryVideo(ctx, r.DB, id)
}

// ChatHistory returns all messages for a session in chronological order.
func (r *queryResolver) ChatHistory(ctx context.Context, sessionID string) ([]*model.ChatMessage, error) {
	rows, err := r.DB.Pool.Query(ctx,
		`SELECT id, session_id, role, content, created_at::text
		 FROM chat_messages WHERE session_id=$1 ORDER BY id ASC`,
		sessionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var msgs []*model.ChatMessage
	for rows.Next() {
		m := &model.ChatMessage{}
		var id, sid int
		rows.Scan(&id, &sid, &m.Role, &m.Content, &m.CreatedAt)
		m.ID = strconv.Itoa(id)
		m.SessionID = strconv.Itoa(sid)
		msgs = append(msgs, m)
	}
	return msgs, nil
}

// UserVideoCount returns the number of non-demo videos the calling user has uploaded.
func (r *queryResolver) UserVideoCount(ctx context.Context) (int32, error) {
	userID := userIDFromCtx(ctx)
	var count int32
	err := r.DB.Pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM videos WHERE user_id=$1 AND is_demo=FALSE`, userID,
	).Scan(&count)
	return count, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
