// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ml.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_proto_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type TranscriptionSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         float32                `protobuf:"fixed32,1,opt,name=start,proto3" json:"start,omitempty"`
	End           float32                `protobuf:"fixed32,2,opt,name=end,proto3" json:"end,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionSegment) Reset() {
	*x = TranscriptionSegment{}
	mi := &file_proto_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionSegment) ProtoMessage() {}

func (x *TranscriptionSegment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionSegment.ProtoReflect.Descriptor instead.
func (*TranscriptionSegment) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptionSegment) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TranscriptionSegment) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *TranscriptionSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscribeResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Language      string                  `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Segments      []*TranscriptionSegment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_proto_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeResponse) GetSegments() []*TranscriptionSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type EmotionRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AudioData     []byte                  `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Segments      []*TranscriptionSegment `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionRequest) Reset() {
	*x = EmotionRequest{}
	mi := &file_proto_ml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionRequest) ProtoMessage() {}

func (x *EmotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionRequest.ProtoReflect.Descriptor instead.
func (*EmotionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{3}
}

func (x *EmotionRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *EmotionRequest) GetSegments() []*TranscriptionSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type EmotionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         float32                `protobuf:"fixed32,1,opt,name=start,proto3" json:"start,omitempty"`
	End           float32                `protobuf:"fixed32,2,opt,name=end,proto3" json:"end,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Emotion       string                 `protobuf:"bytes,4,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionResult) Reset() {
	*x = EmotionResult{}
	mi := &file_proto_ml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionResult) ProtoMessage() {}

func (x *EmotionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionResult.ProtoReflect.Descriptor instead.
func (*EmotionResult) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{4}
}

func (x *EmotionResult) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *EmotionResult) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *EmotionResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmotionResult) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type EmotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*EmotionResult       `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionResponse) Reset() {
	*x = EmotionResponse{}
	mi := &file_proto_ml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionResponse) ProtoMessage() {}

func (x *EmotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionResponse.ProtoReflect.Descriptor instead.
func (*EmotionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ml_proto_rawDescGZIP(), []int{5}
}

func (x *EmotionResponse) GetSegments() []*EmotionResult {
	if x != nil {
		return x.Segments
	}
	return nil
}

var File_proto_ml_proto protoreflect.FileDescriptor

const file_proto_ml_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ml.proto\x12\x04mlpb\"2\n" +
	"\x11TranscribeRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\"R\n" +
	"\x14TranscriptionSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x02R\x03end\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"h\n" +
	"\x12TranscribeResponse\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x126\n" +
	"\bsegments\x18\x02 \x03(\v2\x1a.mlpb.TranscriptionSegmentR\bsegments\"g\n" +
	"\x0eEmotionRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x126\n" +
	"\bsegments\x18\x02 \x03(\v2\x1a.mlpb.TranscriptionSegmentR\bsegments\"\x85\x01\n" +
	"\rEmotionResult\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x02R\x03end\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\aemotion\x18\x04 \x01(\tR\aemotion\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\"B\n" +
	"\x0fEmotionResponse\x12/\n" +
	"\bsegments\x18\x01 \x03(\v2\x13.mlpb.EmotionResultR\bsegments2Y\n" +
	"\x14TranscriptionService\x12A\n" +
	"\n" +
	"Transcribe\x12\x17.mlpb.TranscribeRequest\x1a\x18.mlpb.TranscribeResponse\"\x002S\n" +
	"\x0eEmotionService\x12A\n" +
	"\x10ClassifyEmotions\x12\x14.mlpb.EmotionRequest\x1a\x15.mlpb.EmotionResponse\"\x00BBZ@github.com/yuchia329/video_semantic_search/backend/internal/mlpbb\x06proto3"

var (
	file_proto_ml_proto_rawDescOnce sync.Once
	file_proto_ml_proto_rawDescData []byte
)

func file_proto_ml_proto_rawDescGZIP() []byte {
	file_proto_ml_proto_rawDescOnce.Do(func() {
		file_proto_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ml_proto_rawDesc), len(file_proto_ml_proto_rawDesc)))
	})
	return file_proto_ml_proto_rawDescData
}

var file_proto_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ml_proto_goTypes = []any{
	(*TranscribeRequest)(nil),    // 0: mlpb.TranscribeRequest
	(*TranscriptionSegment)(nil), // 1: mlpb.TranscriptionSegment
	(*TranscribeResponse)(nil),   // 2: mlpb.TranscribeResponse
	(*EmotionRequest)(nil),       // 3: mlpb.EmotionRequest
	(*EmotionResult)(nil),        // 4: mlpb.EmotionResult
	(*EmotionResponse)(nil),      // 5: mlpb.EmotionResponse
}
var file_proto_ml_proto_depIdxs = []int32{
	1, // 0: mlpb.TranscribeResponse.segments:type_name -> mlpb.TranscriptionSegment
	1, // 1: mlpb.EmotionRequest.segments:type_name -> mlpb.TranscriptionSegment
	4, // 2: mlpb.EmotionResponse.segments:type_name -> mlpb.EmotionResult
	0, // 3: mlpb.TranscriptionService.Transcribe:input_type -> mlpb.TranscribeRequest
	3, // 4: mlpb.EmotionService.ClassifyEmotions:input_type -> mlpb.EmotionRequest
	2, // 5: mlpb.TranscriptionService.Transcribe:output_type -> mlpb.TranscribeResponse
	5, // 6: mlpb.EmotionService.ClassifyEmotions:output_type -> mlpb.EmotionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ml_proto_init() }
func file_proto_ml_proto_init() {
	if File_proto_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ml_proto_rawDesc), len(file_proto_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ml_proto_goTypes,
		DependencyIndexes: file_proto_ml_proto_depIdxs,
		MessageInfos:      file_proto_ml_proto_msgTypes,
	}.Build()
	File_proto_ml_proto = out.File
	file_proto_ml_proto_goTypes = nil
	file_proto_ml_proto_depIdxs = nil
}
