// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ml.proto

package mlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscriptionService_Transcribe_FullMethodName = "/mlpb.TranscriptionService/Transcribe"
)

// TranscriptionServiceClient is the client API for TranscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscriptionServiceClient interface {
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
}

type transcriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriptionServiceClient(cc grpc.ClientConnInterface) TranscriptionServiceClient {
	return &transcriptionServiceClient{cc}
}

func (c *transcriptionServiceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_Transcribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscriptionServiceServer is the server API for TranscriptionService service.
// All implementations must embed UnimplementedTranscriptionServiceServer
// for forward compatibility.
type TranscriptionServiceServer interface {
	Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error)
	mustEmbedUnimplementedTranscriptionServiceServer()
}

// UnimplementedTranscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscriptionServiceServer struct{}

func (UnimplementedTranscriptionServiceServer) Transcribe(context.Context, *TranscribeRequest) (*TranscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedTranscriptionServiceServer) mustEmbedUnimplementedTranscriptionServiceServer() {}
func (UnimplementedTranscriptionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTranscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscriptionServiceServer will
// result in compilation errors.
type UnsafeTranscriptionServiceServer interface {
	mustEmbedUnimplementedTranscriptionServiceServer()
}

func RegisterTranscriptionServiceServer(s grpc.ServiceRegistrar, srv TranscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscriptionService_ServiceDesc, srv)
}

func _TranscriptionService_Transcribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).Transcribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_Transcribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).Transcribe(ctx, req.(*TranscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscriptionService_ServiceDesc is the grpc.ServiceDesc for TranscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlpb.TranscriptionService",
	HandlerType: (*TranscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transcribe",
			Handler:    _TranscriptionService_Transcribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ml.proto",
}

const (
	EmotionService_ClassifyEmotions_FullMethodName = "/mlpb.EmotionService/ClassifyEmotions"
)

// EmotionServiceClient is the client API for EmotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmotionServiceClient interface {
	ClassifyEmotions(ctx context.Context, in *EmotionRequest, opts ...grpc.CallOption) (*EmotionResponse, error)
}

type emotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionServiceClient(cc grpc.ClientConnInterface) EmotionServiceClient {
	return &emotionServiceClient{cc}
}

func (c *emotionServiceClient) ClassifyEmotions(ctx context.Context, in *EmotionRequest, opts ...grpc.CallOption) (*EmotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmotionResponse)
	err := c.cc.Invoke(ctx, EmotionService_ClassifyEmotions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionServiceServer is the server API for EmotionService service.
// All implementations must embed UnimplementedEmotionServiceServer
// for forward compatibility.
type EmotionServiceServer interface {
	ClassifyEmotions(context.Context, *EmotionRequest) (*EmotionResponse, error)
	mustEmbedUnimplementedEmotionServiceServer()
}

// UnimplementedEmotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionServiceServer struct{}

func (UnimplementedEmotionServiceServer) ClassifyEmotions(context.Context, *EmotionRequest) (*EmotionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyEmotions not implemented")
}
func (UnimplementedEmotionServiceServer) mustEmbedUnimplementedEmotionServiceServer() {}
func (UnimplementedEmotionServiceServer) testEmbeddedByValue()                        {}

// UnsafeEmotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionServiceServer will
// result in compilation errors.
type UnsafeEmotionServiceServer interface {
	mustEmbedUnimplementedEmotionServiceServer()
}

func RegisterEmotionServiceServer(s grpc.ServiceRegistrar, srv EmotionServiceServer) {
	// If the following call panics, it indicates UnimplementedEmotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionService_ServiceDesc, srv)
}

func _EmotionService_ClassifyEmotions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).ClassifyEmotions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_ClassifyEmotions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).ClassifyEmotions(ctx, req.(*EmotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionService_ServiceDesc is the grpc.ServiceDesc for EmotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlpb.EmotionService",
	HandlerType: (*EmotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyEmotions",
			Handler:    _EmotionService_ClassifyEmotions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ml.proto",
}
